### ISSUE TITLE
Homescreen

### ISSUE THREAD

**Issue by badabam** [badabam/capstone-project-hh-web-21-7#1]
## Value proposition
**As a** user
**I need** a way to track calories
**to be able to** control my weight gain or loss

## Description (text, scribbles, images, designs)
<img width="320" src=https://user-images.githubusercontent.com/157286/142644742-9283101b-157e-41a1-9bb4-09e52892e36a.png >

## Acceptance Criteria
- [ ] All inputs are `required` (browser shows warning if empty)
- [ ] Calory goal should be maxed at 100.000
- [ ] max. 100 characters for Title
- [ ] Amount has to be a integer (no floating point number)
- [ ] Show a number pad for Amount on a mobile device
- [ ] button should be disabled until Title and Amount are filled
- [ ] The title and amount should never overlap in the list
- [ ] The list (pairs of titles and amounts) should scroll vertically on overflow

## Tasks (for developers)
- [ ] Create feature branch
- [ ] Create README
- [ ] Form component
- [ ] List component
- [ ] Calory goal / Calories left component
- [ ] Integrate components into App
- [ ] Setup deployment
